### ISSUE TITLE
ccnunlp.top域名下的服务全部宕机

### ISSUE THREAD

**Issue by ghost** [zengjunjun/CNSD#1]
您好，

http://ccnunlp.top/域名下的服务全部宕机，导致论文、数据集等都无法下载了。
因为非常好奇您是怎样把英文翻译为中文的，所以想要拜读您的论文。

**Comment by pluto-junzeng** [comment]
您好，
非常抱歉，阿里云没钱续费了
目前已更新链接，可以提供下载。
关于翻译，我们使用的是机器翻译的API，撸的各个平台的羊毛。之后进行部分人工修正
谢谢您对 该数据集的关注
祝好

**Comment by ghost** [comment]
> 您好，
> 非常抱歉，阿里云没钱续费了
> 目前已更新链接，可以提供下载。
> 关于翻译，我们使用的是机器翻译的API，撸的各个平台的羊毛。之后进行部分人工修正
> 谢谢您对 该数据集的关注
> 祝好

您好，
请问有多少人参与了对机器翻译的人工修正工作？他们的中英文水平又是怎样的？
祝好

**Comment by pluto-junzeng** [comment]
您好
仅实验室人参与了，英文水平挺高的，但是修正数量不是很多，所以不是全部都修正了。
更多标准化工作，请参考，https://github.com/CLUEbenchmark/CLUE  中的CMNLI 语言推理任务 Chinese Multi-Genre NLI 
谢谢

**Comment by ghost** [comment]
> 您好
> 仅实验室人参与了，英文水平挺高的，但是修正数量不是很多，所以不是全部都修正了。
> 更多标准化工作，请参考，https://github.com/CLUEbenchmark/CLUE 中的CMNLI 语言推理任务 Chinese Multi-Genre NLI
> 谢谢

谢谢回复，已关注CLUE，祝好！
