### ISSUE TITLE
STS-B 数据集无法下载

### ISSUE THREAD

**Issue by LemonNoel** [zengjunjun/CNSD#3]
您好，目前 Chinese-STS-B 的下载链接失效了，请问还会提供新的下载路径吗？

**Comment by aleversn** [comment]
同样的问题

**Comment by Tylerjoe** [comment]
@LemonNoel @aleversn @junzeng-pluto @aleversn 请问在哪可以下载呢？

**Comment by JaneWalden** [comment]
同问
